name: RabbitMQ Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Docker Compose v2
        run: |
          mkdir -p ~/.docker/cli-plugins/
          curl -SL https://github.com/docker/compose/releases/download/v2.37.1/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose
          docker compose version
      - name: Set up Docker Compose
        run: docker compose -f docker-compose.yml up -d
      - name: Wait for RabbitMQ management API
        run: |
          for i in {1..60}; do
            curl -u guest:guest -f http://localhost:15672/api/overview && echo "RabbitMQ management API is ready" && exit 0
            echo "Waiting for RabbitMQ management API..."
            sleep 2
          done
          echo "RabbitMQ management API did not become ready in time" && exit 1
      - name: 安装依赖
        run: pnpm install
      - name: 运行生产者chore: update
        run: node index.js produce
      - name: 运行消费者
        run: |
          timeout 5s node index.js consume || true 